name       : ETL
version    : 1.4.2
release    : 7
source     :
    - https://github.com/synfig/synfig/releases/download/v1.4.2/ETL-1.4.2.tar.gz : e54192d284df16305ddfdfcc5bdfe93e139e6db5bc283dd4bab2413ebbead7c7
license    : GPL-3.0-or-later
component  : programming.library
homepage   : https://www.synfig.org/
summary    : Multi-platform class and template library
description: |
    ETL is a multi-platform class and template library designed to add new datatypes and functions which combine well with the existing types and functions from the C++ Standard Template Library (STL).
patterns   :
    - /
builddeps  :
    - pkgconfig(glibmm-2.4)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
