name       : ETL
version    : 1.5.1
release    : 8
source     :
    - https://github.com/synfig/synfig/releases/download/v1.5.1/ETL-1.5.1.tar.gz : 125c04f1892f285febc2f9cc06f932f7708e3c9f94c3a3004cd1803197197b4a
license    : GPL-3.0-or-later
component  : programming.library
homepage   : https://www.synfig.org/
summary    : Multi-platform class and template library
description: |
    ETL is a multi-platform class and template library designed to add new datatypes and functions which combine well with the existing types and functions from the C++ Standard Template Library (STL).
patterns   :
    - /
builddeps  :
    - pkgconfig(glibmm-2.4)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
