name       : ETL
version    : 1.4.0
release    : 6
source     :
    - https://github.com/synfig/synfig/releases/download/v1.4.0/ETL-1.4.0.tar.gz : d43396c0ac356114713469216a9257247c2588d5475590a46db63cf201d1a011
license    : GPL-3.0-or-later
component  : programming.library
homepage   : https://www.synfig.org/
summary    : Multi-platform class and template library
description: |
    ETL is a multi-platform class and template library designed to add new datatypes and functions which combine well with the existing types and functions from the C++ Standard Template Library (STL).
patterns   :
    - /
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
