name       : ETL
version    : 1.2.2
release    : 5
source     :
    - https://github.com/synfig/synfig/releases/download/v1.2.2/source-ETL-1.2.2.tar.gz : 0dc19c5a6c9e964054ca3af6dacd6ab0c198d78071cfab2aebac178afe454d8b
license    : GPL-3.0-or-later
component  : programming.library
summary    : Multi-platform class and template library
description: |
    ETL is a multi-platform class and template library designed to add new datatypes and functions which combine well with the existing types and functions from the C++ Standard Template Library (STL).
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check