name       : ETL
version    : 0.04.22
release    : 3
source     :
    - https://jaist.dl.sourceforge.net/project/synfig/releases/1.2.0/source/ETL-0.04.22.tar.gz : ac5aeb9b8ec2c69dd455c6c72e104ff20c43e1e5dde6c0cd87f3f7d1b41d2746
license    : GPL-3.0
component  : programming
summary    : Multi-platform class and template library
description: |
    ETL is a multi-platform class and template library designed to add new datatypes and functions which combine well with the existing types and functions from the C++ Standard Template Library (STL).
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
